# Generated by Django 5.1.7 on 2025-08-10 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=20)),
                ('coures', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=7)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ua_enquiry_table',
            },
        ),
    ]
