# Generated by Django 5.1.7 on 2025-08-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquire_form',
            old_name='coures',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enquire_form',
            old_name='model',
            new_name='mode',
        ),
    ]
